# Generated by Django 3.1.7 on 2021-03-13 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0003_auto_20210313_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='message',
            name='last_name',
        ),
    ]
