# Generated by Django 3.1.7 on 2021-03-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0004_auto_20210313_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('link', models.CharField(blank=True, default='#', max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='project_images')),
                ('technology', models.CharField(max_length=100)),
            ],
        ),
    ]
