# Generated by Django 3.1.7 on 2021-03-13 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0006_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
